name: CI/CD Pipeline for Movie Recommender System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 👇 Removed the "Run tests" step

    - name: Build Docker image
      run: |
        docker build -t movie-recommender .

    - name: Push Docker image to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag movie-recommender:latest ${{ secrets.DOCKER_USERNAME }}/movie-recommender:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/movie-recommender:latest
